baseURL = "https://naipia.github.io/"
languageCode = "ja"
title = "naipia"
author = "naipia"
paginate = 10
theme = "hugo-clarity"
enableGitInfo = true

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xhtml = false

[params]
  author = "naipia"
  twitter = "@naipia_"
  #largeTwitterCard = false
  introDescription = ""
  ga_analytics = "UA-179308520-1"
  numberOfTagsShown = 4
  fallBackOgImage = "img/thumbnail.jpg" 
  codeMaxLines = 100
  codeLineNumbers = true
  mainSections = ["blog", "procon"]
  #centerLogo = false
  #logo = ""
  figurePositionShow = false
  #figurePositionLabel = "Figure"
  mobileNavigation = "right"
  customCSS = ["css/custom.css", "css/syntax.css"]
